### ISSUE TITLE
First try

### ISSUE THREAD

**Issue by ThaDafinser** [endorphin-studio/browser-detector#2]
I just wanted to create an abstraction for this package, but it seems to be unfinished yet.
- if you try a bot UserAgent, the lib will throw two warnings and one fatal error
  - example: Tiny Tiny RSS
- if you try a basic userAgent, it does not detect the versions
  - example: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0

**Comment by serhiime** [comment]
@ThaDafinser 
Bot Detection will be soon. I work on it.
Are U sure that "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0" doesn`t detect version. Try Live Demo: http://detector.endorphin-studio.ru/demo/.

**Comment by serhiime** [comment]
@ThaDafinser 
fix fatal error commit: https://github.com/endorphin-studio/browser-detector/commit/967119eebe6a4e9a3d2f649c5829fbd3fed30792
test results: https://travis-ci.org/endorphin-studio/browser-detector/builds/135393248

after adding all robots i will make release and it will appeas in composer package.

**Comment by ThaDafinser** [comment]
I saw you renamed the method to lowercase https://github.com/endorphin-studio/browser-detector/blob/2.0.1/src/Detector.php#L72

Please take care of http://semver.org/ (in this case it will still work)

When you released the new fixed version, i will continue on it
https://github.com/ThaDafinser/UserAgentParser/pull/95/files

**Comment by serhiime** [comment]
@ThaDafinser Yes, That was recommendation from SensioLabInsight to get the platinum badge. 
OK. Thanx for link.
