### ISSUE TITLE
Remove Symfony classloader

### ISSUE THREAD

**Issue by ThaDafinser** [endorphin-studio/browser-detector#4]
Since you use composer, you don't need the Symfony classloader here and in composer.json

https://github.com/endorphin-studio/browser-detector/blob/8bb557baf8dfaf67db04d5bc4631ac6448e7da5e/tests/bootstrap.php#L24-L30

Just do it like this
https://github.com/ThaDafinser/UserAgentParser/blob/master/composer.json#L64-L69

and this
https://github.com/ThaDafinser/UserAgentParser/blob/master/phpunit.xml#L2

**Comment by serhiime** [comment]
fixed in https://github.com/endorphin-studio/browser-detector/commit/8c045a21fd7d255657d23d2aebac765ace64427b
