### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by ThaDafinser** [endorphin-studio/browser-detector#6]
![image](https://cloud.githubusercontent.com/assets/533017/16804057/205e3f0c-490a-11e6-9aaa-2e232ab1a8fa.png)

**Comment by ThaDafinser** [comment]
Getting a lot of them

![image](https://cloud.githubusercontent.com/assets/533017/16804533/956bb6d8-490c-11e6-9fdb-70baeae17788.png)

**Comment by serhiime** [comment]
@ThaDafinser ok. i fix this errors in some days

**Comment by serhiime** [comment]
fixed in https://github.com/endorphin-studio/browser-detector/commit/8c045a21fd7d255657d23d2aebac765ace64427b
