### ISSUE TITLE
[Question] Tag for version 3.0.2

### ISSUE THREAD

**Issue by mimmi20** [endorphin-studio/browser-detector#9]
Could you create a tag for version 3.0.2?

**Comment by serhiime** [comment]
@mimmi20 now i work at 4.0 version with PHP 7.1 and symfony/yaml instead of PHP 5.6 and xml

**Comment by mimmi20** [comment]
@endorphinua You have commits with that version. I thought I you just did forget to push that tag.

**Comment by serhiime** [comment]
@mimmi20 I'm not sure that that commits stable
